version: '3.5'

services:
  postgres:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tinnova_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
     - "5432:5432"